// Code generated by protoc-gen-gogo. DO NOT EDIT.

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

const _ = proto.GoGoProtoPackageIsVersion3 

type Params struct {
	
	IndexNumHeight int64 `protobuf:"varint,1,opt,name=index_num_height,json=indexNumHeight,proto3" json:"index_num_height,omitempty"`
	
	RedeemFeeHeight int64 `protobuf:"varint,2,opt,name=redeem_fee_height,json=redeemFeeHeight,proto3" json:"redeem_fee_height,omitempty"`
	
	RedeemFee github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=redeem_fee,json=redeemFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"redeem_fee"`
	
	MinDelegate types.Coin `protobuf:"bytes,4,opt,name=min_delegate,json=minDelegate,proto3" json:"min_delegate"`
	
	Validity int64 `protobuf:"varint,5,opt,name=validity,proto3" json:"validity,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetIndexNumHeight() int64 {
	if m != nil {
		return m.IndexNumHeight
	}
	return 0
}

func (m *Params) GetRedeemFeeHeight() int64 {
	if m != nil {
		return m.RedeemFeeHeight
	}
	return 0
}

func (m *Params) GetMinDelegate() types.Coin {
	if m != nil {
		return m.MinDelegate
	}
	return types.Coin{}
}

func (m *Params) GetValidity() int64 {
	if m != nil {
		return m.Validity
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "freemasonry.gateway.v1.Params")
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor_f1a937782ebbded5) }

var fileDescriptor_f1a937782ebbded5 = []byte{
	
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xbf, 0xae, 0xda, 0x30,
	0x14, 0xc6, 0x63, 0xa0, 0xa8, 0x98, 0xfe, 0xa1, 0x51, 0x55, 0xa5, 0x0c, 0x09, 0xea, 0x50, 0xa5,
	0x95, 0x6a, 0x8b, 0x76, 0xeb, 0x18, 0x50, 0xd5, 0xa5, 0x55, 0xc5, 0xd8, 0x25, 0x72, 0x9c, 0x43,
	0x62, 0x81, 0x6d, 0x94, 0x04, 0x4a, 0xde, 0xa0, 0x23, 0x6f, 0x50, 0x78, 0x1b, 0x46, 0xc6, 0xea,
	0x0e, 0xe8, 0x0a, 0x96, 0xfb, 0x18, 0x57, 0xf9, 0x03, 0xf7, 0x4e, 0xb6, 0xcf, 0xf7, 0x3b, 0xf6,
	0xf9, 0xfc, 0xe1, 0xe7, 0x11, 0xcb, 0xe0, 0x0f, 0xcb, 0xc9, 0x22, 0xd1, 0x99, 0x36, 0xdf, 0x4c,
	0x13, 0x00, 0xc9, 0x52, 0xad, 0x92, 0x9c, 0x5c, 0xa4, 0xd5, 0xb0, 0xff, 0x3a, 0xd2, 0x91, 0x2e,
	0x11, 0x5a, 0xec, 0x2a, 0xba, 0x6f, 0x73, 0x9d, 0x4a, 0x9d, 0xd2, 0x80, 0xa5, 0x40, 0x57, 0xc3,
	0x00, 0x32, 0x36, 0xa4, 0x5c, 0x0b, 0x55, 0xe9, 0xef, 0xfe, 0x35, 0x70, 0xfb, 0x17, 0x4b, 0x98,
	0x4c, 0x4d, 0x17, 0xf7, 0x84, 0x0a, 0x61, 0xed, 0xab, 0xa5, 0xf4, 0x63, 0x10, 0x51, 0x9c, 0x59,
	0x68, 0x80, 0xdc, 0xe6, 0xe4, 0x45, 0x59, 0xff, 0xb9, 0x94, 0xdf, 0xcb, 0xaa, 0xf9, 0x11, 0xbf,
	0x4a, 0x20, 0x04, 0x90, 0xfe, 0x14, 0xe0, 0x82, 0x36, 0x4a, 0xf4, 0x65, 0x25, 0x7c, 0x03, 0xa8,
	0xd9, 0x1f, 0x18, 0x3f, 0xb0, 0x56, 0x73, 0x80, 0xdc, 0x8e, 0x47, 0xf6, 0x47, 0xc7, 0xb8, 0x39,
	0x3a, 0xef, 0x23, 0x91, 0xc5, 0xcb, 0x80, 0x70, 0x2d, 0x69, 0x3d, 0x67, 0xb5, 0x7c, 0x4a, 0xc3,
	0x19, 0xcd, 0xf2, 0x05, 0xa4, 0x64, 0x0c, 0x7c, 0xd2, 0xb9, 0x5e, 0x6a, 0x7a, 0xf8, 0x99, 0x14,
	0xca, 0x0f, 0x61, 0x0e, 0x85, 0x77, 0xab, 0x35, 0x40, 0x6e, 0xf7, 0xf3, 0x5b, 0x52, 0xf5, 0x91,
	0xc2, 0x26, 0xa9, 0x6d, 0x92, 0x91, 0x16, 0xca, 0x6b, 0x15, 0x6f, 0x4d, 0xba, 0x52, 0xa8, 0x71,
	0xdd, 0x63, 0xf6, 0xf1, 0xd3, 0x15, 0x9b, 0x8b, 0x50, 0x64, 0xb9, 0xf5, 0xa4, 0x9c, 0xfa, 0x7a,
	0xfe, 0xda, 0xbb, 0xdb, 0x3a, 0xe8, 0xef, 0xce, 0x41, 0x9b, 0x9d, 0x83, 0xb6, 0x3b, 0x07, 0x79,
	0xa3, 0xfd, 0xc9, 0x46, 0x87, 0x93, 0x8d, 0x6e, 0x4f, 0x36, 0xda, 0x9c, 0x6d, 0xe3, 0x70, 0xb6,
	0x8d, 0xff, 0x67, 0xdb, 0xf8, 0xfd, 0xe1, 0x71, 0x12, 0x9c, 0xd3, 0x60, 0xae, 0xf9, 0x8c, 0xc7,
	0x4c, 0x28, 0xba, 0xa6, 0x75, 0x32, 0x95, 0x8b, 0xa0, 0x5d, 0xfe, 0xf6, 0x97, 0xfb, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x6b, 0x1c, 0x1e, 0xc5, 0xcc, 0x01, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.IndexNumHeight != that1.IndexNumHeight {
		return false
	}
	if this.RedeemFeeHeight != that1.RedeemFeeHeight {
		return false
	}
	if !this.RedeemFee.Equal(that1.RedeemFee) {
		return false
	}
	if !this.MinDelegate.Equal(&that1.MinDelegate) {
		return false
	}
	if this.Validity != that1.Validity {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Validity != 0 {
		i = encodeVarintGateway(dAtA, i, uint64(m.Validity))
		i--
		dAtA[i] = 0x28
	}
	{
		size, err := m.MinDelegate.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGateway(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.RedeemFee.Size()
		i -= size
		if _, err := m.RedeemFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGateway(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.RedeemFeeHeight != 0 {
		i = encodeVarintGateway(dAtA, i, uint64(m.RedeemFeeHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.IndexNumHeight != 0 {
		i = encodeVarintGateway(dAtA, i, uint64(m.IndexNumHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGateway(dAtA []byte, offset int, v uint64) int {
	offset -= sovGateway(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IndexNumHeight != 0 {
		n += 1 + sovGateway(uint64(m.IndexNumHeight))
	}
	if m.RedeemFeeHeight != 0 {
		n += 1 + sovGateway(uint64(m.RedeemFeeHeight))
	}
	l = m.RedeemFee.Size()
	n += 1 + l + sovGateway(uint64(l))
	l = m.MinDelegate.Size()
	n += 1 + l + sovGateway(uint64(l))
	if m.Validity != 0 {
		n += 1 + sovGateway(uint64(m.Validity))
	}
	return n
}

func sovGateway(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGateway(x uint64) (n int) {
	return sovGateway(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGateway
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IndexNumHeight", wireType)
			}
			m.IndexNumHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IndexNumHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RedeemFeeHeight", wireType)
			}
			m.RedeemFeeHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RedeemFeeHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RedeemFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGateway
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGateway
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RedeemFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinDelegate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGateway
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGateway
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinDelegate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validity", wireType)
			}
			m.Validity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Validity |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGateway(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGateway
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGateway(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGateway
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGateway
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGateway
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGateway
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGateway        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGateway          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGateway = fmt.Errorf("proto: unexpected end of group")
)
